controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["chassis_to_leftWheel"]
    right_wheel_names: ["chassis_to_rightWheel"]

    wheel_separation: 0.2667
    wheel_radius: 0.0559

    publish_rate: 20.0

    open_loop: true

    odom_frame_id: odom
    base_frame_id: chassis
    enable_odom_tf: true
    tf_frame_prefix_enable: false

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 20.0
